import { UserRecord, ActivityLog, AlertRecord, ComplianceItem } from '../types';

export const mockUsers: UserRecord[] = [
  {
    id: 'U101',
    name: 'Alice Smith',
    email: 'alice.smith@inditech.bank',
    department: 'Security Operations',
    role: 'SOC Analyst',
    privileges: ['Read Alerts', 'Investigate', 'Trigger Actions'],
    riskScore: 12,
    baselineRiskScore: 12,
    status: 'ACTIVE',
    avatar: 'https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=150',
    location: 'Mumbai, India',
    lastLogin: '2026-07-14T08:30:00Z',
  },
  {
    id: 'U102',
    name: 'Bob Johnson',
    email: 'bob.johnson@inditech.bank',
    department: 'Infrastructure',
    role: 'Security Administrator',
    privileges: ['Configure Firewall', 'Manage Policy', 'Read Logs'],
    riskScore: 18,
    baselineRiskScore: 18,
    status: 'ACTIVE',
    avatar: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=150',
    location: 'Mumbai, India',
    lastLogin: '2026-07-14T09:15:00Z',
  },
  {
    id: 'U103',
    name: 'Charlie Brown',
    email: 'charlie.brown@inditech.bank',
    department: 'Internal Audit',
    role: 'Auditor',
    privileges: ['View Compliance', 'Export Reports', 'Read Audit Logs'],
    riskScore: 22,
    baselineRiskScore: 22,
    status: 'ACTIVE',
    avatar: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=150',
    location: 'Delhi, India',
    lastLogin: '2026-07-14T07:45:00Z',
  },
  {
    id: 'U104',
    name: 'David Miller',
    email: 'david.miller@inditech.bank',
    department: 'IT Systems',
    role: 'System Administrator',
    privileges: ['Root Access', 'User Management', 'Database Administrator', 'Execute Commands'],
    riskScore: 15,
    baselineRiskScore: 15,
    status: 'ACTIVE',
    avatar: 'https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?w=150',
    location: 'Mumbai, India',
    lastLogin: '2026-07-14T10:00:00Z',
  },
  {
    id: 'U105',
    name: 'Emma Davis',
    email: 'emma.davis@inditech.bank',
    department: 'Finance',
    role: 'Payroll Manager',
    privileges: ['Access Financial Databases', 'Process Payroll', 'Download Payroll File'],
    riskScore: 25,
    baselineRiskScore: 25,
    status: 'ACTIVE',
    avatar: 'https://images.unsplash.com/photo-1438761681033-6461ffad8d80?w=150',
    location: 'Bangalore, India',
    lastLogin: '2026-07-14T09:00:00Z',
  },
  {
    id: 'U106',
    name: 'Frank Wilson',
    email: 'frank.wilson@inditech.bank',
    department: 'Risk Management',
    role: 'Risk Manager',
    privileges: ['Access Risk Dashboards', 'Configure Alert Thresholds'],
    riskScore: 14,
    baselineRiskScore: 14,
    status: 'ACTIVE',
    avatar: 'https://images.unsplash.com/photo-1519085360753-af0119f7cbe7?w=150',
    location: 'Mumbai, India',
    lastLogin: '2026-07-14T08:15:00Z',
  }
];

export const baselineActivities: ActivityLog[] = [
  {
    id: 'A501',
    userId: 'U101',
    userName: 'Alice Smith',
    userRole: 'SOC Analyst',
    department: 'Security Operations',
    action: 'Employee Login',
    module: 'Authentication',
    ip: '10.120.45.12',
    device: 'IN-SOC-L01',
    browser: 'Chrome',
    os: 'Windows 11',
    location: 'Mumbai, India',
    timestamp: '2026-07-14T08:30:00Z',
    riskScore: 5,
    status: 'ALLOWED',
  },
  {
    id: 'A502',
    userId: 'U105',
    userName: 'Emma Davis',
    userRole: 'Payroll Manager',
    department: 'Finance',
    action: 'Employee Login',
    module: 'Authentication',
    ip: '10.120.55.8',
    device: 'IN-FIN-L04',
    browser: 'Firefox',
    os: 'Windows 11',
    location: 'Bangalore, India',
    timestamp: '2026-07-14T09:00:00Z',
    riskScore: 8,
    status: 'ALLOWED',
  },
  {
    id: 'A503',
    userId: 'U102',
    userName: 'Bob Johnson',
    userRole: 'Security Administrator',
    department: 'Infrastructure',
    action: 'Admin Login',
    module: 'Authentication',
    ip: '10.120.45.2',
    device: 'IN-NET-L02',
    browser: 'Chrome',
    os: 'Windows 11',
    location: 'Mumbai, India',
    timestamp: '2026-07-14T09:15:00Z',
    riskScore: 10,
    status: 'ALLOWED',
  },
  {
    id: 'A504',
    userId: 'U105',
    userName: 'Emma Davis',
    userRole: 'Payroll Manager',
    department: 'Finance',
    action: 'Database Access - Payroll DB',
    module: 'Database',
    ip: '10.120.55.8',
    device: 'IN-FIN-L04',
    browser: 'Firefox',
    os: 'Windows 11',
    location: 'Bangalore, India',
    timestamp: '2026-07-14T09:22:00Z',
    riskScore: 12,
    status: 'ALLOWED',
  },
  {
    id: 'A505',
    userId: 'U104',
    userName: 'David Miller',
    userRole: 'System Administrator',
    department: 'IT Systems',
    action: 'Admin Login',
    module: 'Authentication',
    ip: '10.120.10.1',
    device: 'IN-SYS-L01',
    browser: 'Chrome',
    os: 'Windows 11',
    location: 'Mumbai, India',
    timestamp: '2026-07-14T10:00:00Z',
    riskScore: 15,
    status: 'ALLOWED',
  },
  {
    id: 'A506',
    userId: 'U102',
    userName: 'Bob Johnson',
    userRole: 'Security Administrator',
    department: 'Infrastructure',
    action: 'Firewall Policy Change - Added Port 443 Rule',
    module: 'Network',
    ip: '10.120.45.2',
    device: 'IN-NET-L02',
    browser: 'Chrome',
    os: 'Windows 11',
    location: 'Mumbai, India',
    timestamp: '2026-07-14T10:15:00Z',
    riskScore: 18,
    status: 'ALLOWED',
  },
  {
    id: 'A507',
    userId: 'U103',
    userName: 'Charlie Brown',
    userRole: 'Auditor',
    department: 'Internal Audit',
    action: 'Audit Log Export',
    module: 'Compliance',
    ip: '10.120.30.5',
    device: 'IN-AUD-L01',
    browser: 'Edge',
    os: 'Windows 10',
    location: 'Delhi, India',
    timestamp: '2026-07-14T10:30:00Z',
    riskScore: 10,
    status: 'ALLOWED',
  }
];

export const baselineAlerts: AlertRecord[] = [
  {
    id: 'ALT-2026-001',
    userId: 'U105',
    userName: 'Emma Davis',
    department: 'Finance',
    severity: 'MEDIUM',
    riskScore: 45,
    description: 'Off-hours database access followed by local download',
    timestamp: '2026-07-13T22:15:00Z',
    aiConfidence: 82,
    assignedAnalyst: 'Alice Smith',
    status: 'CLOSED',
    evidence: ['Database query: SELECT * FROM payroll_master', 'Local file write: payroll_2026_q2.xlsx (4.5 MB)'],
    explanation: 'User Emma Davis accessed payroll master schema at 10:15 PM, which is outside her typical working hours of 9:00 AM - 6:00 PM. A small file was subsequently downloaded. SOC Analyst resolved this as pre-authorized monthly processing activity.',
  },
  {
    id: 'ALT-2026-002',
    userId: 'U102',
    userName: 'Bob Johnson',
    department: 'Infrastructure',
    severity: 'LOW',
    riskScore: 28,
    description: 'Multiple failed login attempts from standard office IP',
    timestamp: '2026-07-14T09:05:00Z',
    aiConfidence: 94,
    assignedAnalyst: 'Alice Smith',
    status: 'CLOSED',
    evidence: ['3 failed LDAP authentication attempts in 60 seconds', 'Successful login on 4th attempt with MFA'],
    explanation: 'Bob Johnson entered an incorrect password three times before successfully authenticating. This occurred from his registered office workstation. Flagged as human error.',
  }
];

export const complianceItems: ComplianceItem[] = [
  {
    id: 'RBI-001',
    standard: 'RBI Security Compliance',
    control: 'Multi-Factor Authentication (MFA) Implementation',
    status: 'COMPLIANT',
    evidence: 'MFA enforced for 100% of employees, contractors, and administrators.',
    lastAudited: '2026-06-15T00:00:00Z',
  },
  {
    id: 'RBI-002',
    standard: 'RBI Security Compliance',
    control: 'Privileged Access Management (PAM) & Activity Logging',
    status: 'UNDER_REVIEW',
    evidence: 'Privileged user logs captured. High-risk activities require real-time risk evaluation.',
    lastAudited: '2026-07-01T00:00:00Z',
  },
  {
    id: 'RBI-003',
    standard: 'RBI Security Compliance',
    control: 'Database Encryption at Rest and in Transit',
    status: 'COMPLIANT',
    evidence: 'AES-256 for storage; TLS 1.3 enforced for database connections.',
    lastAudited: '2026-06-10T00:00:00Z',
  },
  {
    id: 'ISO-27001-A9',
    standard: 'ISO 27001',
    control: 'Access Control Policy and User Registration',
    status: 'COMPLIANT',
    evidence: 'Formally documented access provisioning and de-provisioning workflows.',
    lastAudited: '2026-05-20T00:00:00Z',
  },
  {
    id: 'ISO-27001-A12',
    standard: 'ISO 27001',
    control: 'Operations Security - Logging and Monitoring',
    status: 'COMPLIANT',
    evidence: 'Centralized SIEM collects OS, network, and application security events.',
    lastAudited: '2026-07-10T00:00:00Z',
  },
  {
    id: 'ISO-27001-A14',
    standard: 'ISO 27001',
    control: 'System Acquisition, Development and Maintenance',
    status: 'NON-COMPLIANT',
    evidence: 'Source code scanning (SAST) missing for legacy commercial banking APIs.',
    lastAudited: '2026-07-05T00:00:00Z',
  }
];
